on:
  release:
    types: [created]

jobs:
  preset:
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: jq zip
  run:
    needs: preset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Logic-Sugar-135
            minGameVersion: 135
          - name: Logic-Sugar-146
            minGameVersion: 136
          - name: Logic-Sugar-147
            minGameVersion: 146
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Preset subdir
        run: |
          cp src -vr ${{ matrix.name }} &&
          cd "$_" &&
          cp ../README.md -v . &&
          git log HEAD^..HEAD --pretty=fuller | tee git.log

      - name: Set minGameVersion
        run: |
          cd ${{ matrix.name }} &&
          jq .minGameVersion=${{ matrix.minGameVersion }} mod.json \
          | tee tmp.json &&
          mv -v tmp.json mod.json

      - name: Pack
        run: |
          mkdir -p output &&
            cd ${{ matrix.name }} &&
            zip ../output/${{ matrix.name }}-"v$(jq -r .version mod.json)".zip -9 -r .

      - name: Upload
        run: |
          gh release upload "v$(jq -r .version src/mod.json)" output/${{ matrix.name }}*
