name: Auto Pack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        uses: ConorMacBride/install-package@v1
        with:
          apt: jq
  modify-version-and-upload:
    needs: set-env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Logic-Sugar-135
            minGameVersion: 135
          - name: Logic-Sugar-146
            minGameVersion: 136
          - name: Logic-Sugar-147
            minGameVersion: 146
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Preset subdir
        run: |
          cp src -r ${{ matrix.name }} &&
          cd "$_" &&
          cp ../README.md . &&
          git log --pretty=fuller | tee git.log

      - name: Set minGameVersion
        run: |
          cd ${{ matrix.name }} &&
          jq .minGameVersion=${{ matrix.minGameVersion }} mod.json \
          | tee tmp.json &&
          mv -v tmp.json mod.json
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}
